# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        default: 'juanserv'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.event.inputs.environment }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds:  ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check az providers and feature registration
        uses: azure/CLI@1.0.4
        with:
          azcliversion: latest
          inlineScript: |
            #constants
            BLUE='\033[1;34m'
            RED='\033[1;31m'
            NC='\033[0m'
            errorState=0

            # Check provider list
            providers=("Microsoft.VirtualMachineImages" "Microsoft.KeyVault" "Microsoft.Compute" "Microsoft.Storage" "Microsoft.Network")
            for provider in ${providers[@]}; do
              state=$(az provider show --namespace ${provider} -o tsv --query registrationState)
              if [ $state != 'Registered' ]; then
                      echo -e "::error::Account not registered for provider ${provider}\nPlease run this in your account:\n\t${BLUE}az provider register --namespace ${provider}${NC}"
                      errorState=1
              else
                      echo "::debug::Provider ${provider} registered!"
              fi
            done

            #check vm template feature (needed because it's still in preview)

            state=$(az feature show --namespace Microsoft.VirtualMachineImages --name VirtualMachineTemplatePreview -o tsv --query properties.state)
            if [ $state != 'Registered' ]; then
                    echo -e "::error::Account not registered for VirtualMachineTemplatePreview\nPlease run this in your account:\n\t${BLUE}az feature register --namespace Microsoft.VirtualMachineImages --name VirtualMachineTemplatePreview${NC}"
                    errorState=1
            else
                    echo "::debug::Feature registered!"
            fi

            exit $errorState

      - name: Build image
        uses: azure/CLI@1.0.4
        env:
          RESOURCE_GROUP: 'marketplace-image-demo'
          IMAGE_DEF_NAME: 'myimagedefname'
          GALLERY_NAME: 'myimagegal'
          REGION1: 'northeurope'
          REGION2: 'westeurope'
          OUTNAME: 'aibLinuxCustom'
          IDENTITY: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          azcliversion: latest
          inlineScript: |
            ls -laF

            grep "id" <<< $IDENTITY                      

            ACCOUNT_ID=$(az account show --query id -o tsv)
            sed -i -e "s/<subscriptionID>/$ACCOUNT_ID/g" createimage.json
            sed -i -e "s/<rgName>/$RESOURCE_GROUP/g" createimage.json
            sed -i -e "s/<imageDefName>/$IMAGE_DEF_NAME/g" createimage.json
            sed -i -e "s/<region1>/$REGION1/g" createimage.json
            sed -i -e "s/<region2>/$REGION2/g" createimage.json
            sed -i -e "s/<runOutputName>/$OUTNAME/g" createimage.json
            sed -i -e "s/<imgBuilderId>/$BUILDERID/g" createimage.json

            cat createimage.json

            az resource create -g $RESOURCE_GROUP --properties @createimage.json --is-full-object --resource-type Microsoft.VirtualMachineImages/imageTemplates -n simpleImageTemplate01
            